XiaoHui:
  Path: "/data/xiaohui"
  SSHPath: "/root/.ssh"
  AudioPath: "/data/xiaohui/mp3"
  DocsPath: "/data/xiaohui/docs"
cron:
  name: cron
  log:
    DefaultPath: "/data/xiaohui/logs/cron/default.log"
    ErrorPath: "/data/xiaohui/logs/cron/errors.log"
    MaxSize: 128
  jobs:
    - name: audio
      spec: "0 13 8,9,12,16,20 * * *"
      enabled: true
